name: Build Only Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
              
      - name: Install WiX
        run: dotnet tool install --global wix || echo "Wix already installed or handled by Gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Windows Targets
        run: ./gradlew :composeApp:packageReleaseExe :composeApp:packageReleaseMsi
        
      - name: Dump jpackage logs
        shell: pwsh
        run: |
          Get-ChildItem "composeApp\build\compose\logs\packageReleaseExe" | Format-Table Name,Length
          "`n--- ERR ---`n"
          Get-Content "composeApp\build\compose\logs\packageReleaseExe\jpackage-*-err.txt"
          "`n--- OUT ---`n"
          Get-Content "composeApp\build\compose\logs\packageReleaseExe\jpackage-*-out.txt"
      
            
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            composeApp/build/compose/binaries/main-release/exe/*.exe
            composeApp/build/compose/binaries/main-release/msi/*.msi
